{
 "title": "National Dashboard",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "panels": [
  { "title": "TODAY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ISSUES SUBMITTED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere    DAYOFYEAR(created_date) = DAYOFYEAR(now())\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(CASE WHEN current_status = 'CLOSED' then 'CLOSED'  end) as 'CLOSED'\nfrom incidents_incident\nwhere  DAYOFYEAR(created_date) = DAYOFYEAR(now())\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere  current_status = 'ACTION_PENDING' || 'ACTION_TAKEN' || 'INFORMATION_PROVIDED' || 'INFORMATION_REQESTED' || 'VERIFIED' || 'REOPENED' and   DAYOFYEAR(created_date) = DAYOFYEAR(now())\nGROUP BY current_status"
    }
   ]
  },
  { "title": "FOR THE GIVEN TIME RANGE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "ISSUES SUBMITED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere    $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(CASE WHEN current_status = 'CLOSED' || 'INVALIDATED' then 'CLOSED'  end) as 'CLOSED'\nfrom incidents_incident\nwhere $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "PENDING",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*) as value\nfrom incidents_incident\nwhere \n(current_status = 'ACTION_PENDING' or  \ncurrent_status = 'INFORMATION_REQUESTED') and \n$__timeFilter(created_date)\n\nGROUP BY id"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*) as value\nfrom incidents_incident\nwhere \n(current_status = 'ACTION_TAKEN' or  \ncurrent_status = 'ACTION_PENDING' or \ncurrent_status = 'ADVICE_PROVIDED' or \ncurrent_status = 'ADVICE_REQESTED' or\ncurrent_status = 'VERIFIED' or\ncurrent_status = 'REOPENED') and \n$__timeFilter(created_date)\n\nGROUP BY id"
    }
   ]
  },
  {
   "title": "NEW / UNVERIFIED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere  current_status = 'NEW' and  $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "VERIFIED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect created_date as \"time\",\ncount(*)\nfrom incidents_incident\nwhere  current_status = 'VERIFIED' and  $__timeFilter(created_date)\nGROUP BY current_status"
    }
   ]
  },
  { "title": "OVERALL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "ISSUES SUBMITTED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(*)\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "NEW / UNVERIFIED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'NEW' then 'NEW'  end) as 'NEW'\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "VERIFIED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'VERIFIED' then 'VERIFIED'  end) as 'VERIFIED'\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "ASSIGNED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'ACTION_PENDING'  then 'ASSIGNED'  end) as 'ASSIGNED'\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "ACTION PENDING / INFORMATION REQUESTED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'ACTION_PENDING' || 'INFORMATION_REQUESTED'  then 'PENDING'  end) as 'PENDING'\n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "IN-PROGRESS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(*) as 'ACTIVE' \n--   count(CASE WHEN current_status != 'RESOLVED' then 'Unresolved' end) as Unresolved,\nfrom incidents_incident\nwhere \ncurrent_status = 'ACTION_TAKEN' or  \ncurrent_status = 'INFORMATION_PROVIDED' or \ncurrent_status = 'REOPENED'\n\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "INVALIDATED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'INVALIDATED' then 'INVALIDATED'  end) as 'INVALIDATED'\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  },
  {
   "title": "CLOSED",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "\nselect occured_date as \"time\",\ncount(CASE WHEN current_status = 'CLOSED' || 'INVALIDATED' then 'CLOSED'  end) as 'CLOSED'\nfrom incidents_incident\nGROUP BY current_status"
    }
   ]
  }
 ]
}